# Generated by Django 4.1.7 on 2023-03-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=150)),
                ('pershkrimi', models.TextField(max_length=500)),
                ('imazhi', models.ImageField(null=True, upload_to='postimet')),
                ('slug', models.SlugField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.kategori')),
            ],
        ),
    ]
