# Generated by Django 4.1.7 on 2023-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimi',
            name='index',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='postimi',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
